### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Mahdiford** [bhomaidan1990/yumi_ros#2]
I have tried this repo with all three firmware backups. The "14000-501950_RWS_ROS_EGM_2021-11-12" is the only one that worked with this example "roslaunch yumi_launch yumi_traj_pos_control.launch".  But for "myLaunch" and "roslaunch yumi_launch yumi_traj_vel_control.launch" I got this error "Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)".

With the first launch file I mentioned, I am sure the connection between YuMi and PC is fine. Also, I have loaded my EGM license when creating the Robotware image. Any suggestion would be appreciated. 
Also, thanks for porting this repo to Noetic.

**Comment by bhomaidan1990** [comment]
@Mahdiford Please provide more details, did you install the Socket Server on YuMi? What are the messages you get on the Flexpandant? I usually use `myLaunch.launch` were you able to move the robot using `traj_pos_controller`?? What are the tasks running on Flexpandant??

**Comment by Mahdiford** [comment]
> @Mahdiford Please provide more details, did you install the Socket Server on YuMi? What are the messages you get on the Flexpandant? I usually use `myLaunch.launch` were you able to move the robot using `traj_pos_controller`?? What are the tasks running on Flexpandant??

On the robot side "T_ROB_L", "T_ROB_R", "ROS_StateServer", "T_Gripmotio_x" and "T_Grip_State" are running. Also, it confirms that a client at my PC address is connected after I run the myLaunch on the PC side. And when I execute the myLaunch I got this error "[ WARN] [1655670421.101692493]: Trajectory state not received for 1.000000 seconds
[ INFO] [1655670423.828796955]: Loading robot model 'yumi'...
[ INFO] [1655670424.208861117]: Starting planning scene monitor
[ INFO] [1655670424.210470749]: Listening to '/move_group/monitored_planning_scene'
[ERROR] [1655670424.699879193]: Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)
[ WARN] [1655670424.699931881]: Not connected, bytes not received
[ERROR] [1655670424.699942581]: Failed to receive message length
[ERROR] [1655670424.699952682]: Failed to receive incoming message
[ WARN] [1655670424.699963843]: Send failure, no callback support
"

**Comment by Mahdiford** [comment]
Wrong rapid files were uploaded to the robot. In this [link](https://github.com/kth-ros-pkg/yumi/wiki/Firmware) follow ABB Driver and gripper. Thank you @bhomaidan1990 for porting to Noetic.
